<?xml version="1.0" encoding="utf-8"?><Database Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.v_esdisp_revenue_forecast" Member="revenue_forecasts">
    <Type Name="revenue_forecast">
      <Column Name="psl" Type="System.String" DbType="Char(2) " IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="rec_id" Type="System.Int32" DbType="Int" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="disp_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="formatted_disp_id" Type="System.String" CanBeNull="false" />
      <Column Name="revenue_year" Type="System.Int32" DbType="int" CanBeNull="false" />
      <Column Name="revenue_month" Type="System.Int32" DbType="int" CanBeNull="false" />
      <Column Name="status" Type="System.Int16" DbType="smallint" CanBeNull="true" />
      <Column Name="status_desc" Type="System.String" CanBeNull="false" />
      <Column Name="dist_id" Type="System.Int32" DbType="int" CanBeNull="false" />
      <Column Name="oilcomp_id" Type="System.String" CanBeNull="false" />
      <Column Name="well_name" Type="System.String" CanBeNull="false" />
      <Column Name="service_list" Type="System.String" CanBeNull="false" />
      <Column Name="sales_rep_employee_id" Type="System.String" CanBeNull="false" />
      <Column Name="dispatch_offline_flag" Type="System.Boolean" DbType="bit" CanBeNull="false" />
      <Column Name="critical_job_flag" Type="System.Boolean" DbType="bit" CanBeNull="false" />
      <Column Name="job_approved_state" Type="System.Byte" DbType="tinyint" CanBeNull="true" />
      <Column Name="revenue" Type="System.Decimal" DbType="decimal(15,2)" CanBeNull="true" />
      <Column Name="optional_revenue" Storage="_optional_quote_revenue" Type="System.Decimal" DbType="decimal(15,2)" CanBeNull="true" />
      <Column Name="total_fso_count" Type="System.Int32" DbType="int" CanBeNull="true" />
      <Column Name="exported_fso_count" Type="System.Int32" DbType="int" CanBeNull="true" />
      <Column Name="total_quote_count" Type="System.Int32" DbType="int" CanBeNull="true" />
      <Column Name="exported_quote_count" Type="System.Int32" DbType="int" CanBeNull="true" />
      <Column Name="opportunity_revenue" Type="System.Decimal" DbType="decimal(15, 2)" CanBeNull="true" />
      <Column Name="opportunity_probability" Type="System.Decimal" DbType="decimal(5,2)" CanBeNull="true" />
      <Column Name="risk_revenue" Type="System.Decimal" DbType="decimal(15,2)" CanBeNull="true" />
      <Column Name="risk_probability" Type="System.Decimal" DbType="decimal(5,2)" CanBeNull="true" />
      <Column Name="comment" Type="System.String" CanBeNull="false" />
      <Column Name="main_quote_count" Type="System.Int32" DbType="int" CanBeNull="true" />
      <Column Name="original_disp_revenue" Type="System.Decimal" DbType="decimal(15, 2)" CanBeNull="true" />
    </Type>
  </Table>
</Database>