'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("["&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&"{""ColumnName"":""grcQuoteStatus"",""ColumnHeader"":""Q"",""DefaultDisplayIndex"":0,""De"& _ 
            "faultWidth"":20.0,""CanUserReorder"":false,""CanUserSetVisibility"":false,""DisplayInd"& _ 
            "ex"":0,""IsHidden"":false},"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&"{""ColumnName"":""grcFsoStatus"",""ColumnHeader"":""F"",""Defa"& _ 
            "ultDisplayIndex"":1,""DefaultWidth"":24.0,""CanUserReorder"":false,""CanUserSetVisibil"& _ 
            "ity"":false,""DisplayIndex"":1,""IsHidden"":false},"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&"{""ColumnName"":""grcJobApprovedSt"& _ 
            "atus"",""ColumnHeader"":""Ap"",""DefaultDisplayIndex"":2,""DefaultWidth"":24.0,""CanUserRe"& _ 
            "order"":false,""CanUserSetVisibility"":false,""DisplayIndex"":2,""IsHidden"":false},"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)& _ 
            "{""ColumnName"":""grcYear"",""ColumnHeader"":""Year"",""DefaultDisplayIndex"":3,""DefaultWi"& _ 
            "dth"":40.0,""CanUserReorder"":false,""CanUserSetVisibility"":false,""DisplayIndex"":3,"""& _ 
            "IsHidden"":false},"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&"{""ColumnName"":""grcPeriod"",""ColumnHeader"":""Period"",""DefaultDi"& _ 
            "splayIndex"":4,""DefaultWidth"":40.0,""CanUserReorder"":false,""CanUserSetVisibility"":"& _ 
            "false,""DisplayIndex"":4,""IsHidden"":false},"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&"{""ColumnName"":""grcJobOrderId"",""Colum"& _ 
            "nHeader"":""Job Order ID"",""DefaultDisplayIndex"":5,""DefaultWidth"":80.0,""CanUserReor"& _ 
            "der"":false,""CanUserSetVisibility"":false,""DisplayIndex"":5,""IsHidden"":false},"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&"{"""& _ 
            "ColumnName"":""grcDistrict"",""ColumnHeader"":""District"",""DefaultDisplayIndex"":6,""Def"& _ 
            "aultWidth"":140.0,""CanUserReorder"":false,""CanUserSetVisibility"":false,""DisplayInd"& _ 
            "ex"":6,""IsHidden"":true},"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&"{""ColumnName"":""grcCustomer"",""ColumnHeader"":""Customer"","& _ 
            """DefaultDisplayIndex"":7,""DefaultWidth"":180.0,""CanUserReorder"":false,""CanUserSetV"& _ 
            "isibility"":false,""DisplayIndex"":8,""IsHidden"":false},"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&"{""ColumnName"":""grcWellNam"& _ 
            "e"",""ColumnHeader"":""Well Name"",""DefaultDisplayIndex"":8,""DefaultWidth"":140.0,""CanU"& _ 
            "serReorder"":true,""CanUserSetVisibility"":true,""DisplayIndex"":9,""IsHidden"":false},"& _ 
            ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&"{""ColumnName"":""grcServices"",""ColumnHeader"":""Services"",""DefaultDisplayIndex"":9"& _ 
            ",""DefaultWidth"":140.0,""CanUserReorder"":true,""CanUserSetVisibility"":true,""Display"& _ 
            "Index"":10,""IsHidden"":false},"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&"{""ColumnName"":""grcSalesRep"",""ColumnHeader"":""Sales"& _ 
            " Person"",""DefaultDisplayIndex"":10,""DefaultWidth"":140.0,""CanUserReorder"":true,""Ca"& _ 
            "nUserSetVisibility"":true,""DisplayIndex"":7,""IsHidden"":false}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"]"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property UserConfig() As String
            Get
                Return CType(Me("UserConfig"),String)
            End Get
            Set
                Me("UserConfig") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DefaultConfig() As String
            Get
                Return CType(Me("DefaultConfig"),String)
            End Get
            Set
                Me("DefaultConfig") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ListViewGridViewTest.My.MySettings
            Get
                Return Global.ListViewGridViewTest.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
